yaml fix

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -15,35 +15,35 @@ jobs:
           node-version: ${{ env.NODE_VERSION }}
       - run: npm ci
       - run: npm run build
-
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: 'javascript'
-        queries: security-extended
-    
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        upload: true
-        category: "/language:javascript"
-        ram: 4096
-        threads: 2
-
-    - name: Check for vulnerable dependencies
-      run: npm audit
-
-    - name: Scan for secrets
-      run: |
-        output=$(docker run --rm -v "$(pwd)":/code trufflesecurity/trufflehog:latest \
-        filesystem --directory=/code \
-        --exclude-paths='node_modules,dist,test' \
-        --json)
-        
-        if [ -n "$output" ]; then
-          echo "::error::Secrets found! Check logs for details."
-          echo "$output"
-          exit 1
-        fi
+      
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v3
+        with:
+          languages: 'javascript'
+          queries: security-extended
+      
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v3
+        with:
+          upload: true
+          category: "/language:javascript"
+          ram: 4096
+          threads: 2
+      
+      - name: Check for vulnerable dependencies
+        run: npm audit
+      
+      - name: Scan for secrets
+        run: |
+          output=$(docker run --rm -v "$(pwd)":/code trufflesecurity/trufflehog:latest \
+          filesystem --directory=/code \
+          --exclude-paths='node_modules,dist,test' \
+          --json)
+          
+          if [ -n "$output" ]; then
+            echo "::error::Secrets found! Check logs for details."
+            echo "$output"
+            exit 1
+          fi
 
       
